# Generated by Django 4.2.2 on 2023-10-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_loginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='userx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='timelogin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
