# Generated by Django 4.2.2 on 2023-10-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0003_remove_loginmodel_user_loginmodel_userx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='userx',
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
